version: "3.9"

services:
  mariadb:
    image: mariadb:11.4
    container_name: edufika-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: edufika
      MARIADB_USER: edufika
      MARIADB_PASSWORD: edufika
    ports:
      - "3306:3306"
    volumes:
      - edufika_mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: edufika-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8089:80"

volumes:
  edufika_mariadb_data:
